aviaServer/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from products.views import index
from django.urls import path, include

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', index, name='index'),
    path('', include('products.urls', namespace='products')),
    path('oversight/', include('supervision.urls', namespace='supervision')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


supervision/urls.py
from django.urls import path
from supervision.views import control, supervise, delete_check_month, add_check_month, dashboard, create_period, move_check
from documents.views import  update_move_check, get_moved, post

app_name = "supervision"

urlpatterns = [
    path('<slug:company_slug>/', control, name='control'),
    path('<slug:company_slug>/edit', control, {'edit': True}, name='edit'),
    path('<slug:company_slug>/dashboard/', dashboard, name='dashboard'),
    path('<slug:company_slug>/check-area-table/', supervise, name='check_area_table'),
    path('<slug:company_slug>/moved/', get_moved, name='moved'),
    path('<slug:company_slug>/add-period/', create_period, name='period'),
    path('api/post', post, name='post'),
    path('api/<int:month_id>/delete/', delete_check_month, name='delete_check_month'),
    path('api/<int:area_id>/<int:month_id>/add/', add_check_month, name='add_check_month'),
    path('api/move-check/<int:area_id>/', move_check, name='move'),
    path('api/post-move-check/<slug:company_slug>/', update_move_check, name='update_move'),

]

users/urls.py
from users.views import register, login, profile, forgot_password, logout, user_list, grant_access, update_perm, delete_user, delete_company, edit_user, point
from django.urls import path

app_name = 'users'
urlpatterns = [
    path('', user_list, name='user_list'),
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('restore-password/', forgot_password, name='password'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('api/<slug:user_slug>/update-permission', update_perm, name='update_perm'),
    path('<slug:user_slug>/', edit_user, name='edit_user'),
    path('<slug:user_slug>/update-permission/', point, name='permission'),
    path('<slug:user_slug>/delete', delete_user, name='delete_user'),
    path('<slug:company_slug>/delete', delete_company, name='delete_company'),
    path('<slug:user_slug>/grant_access/', grant_access, name='grant_access'),

]

supervision/forms.py
from datetime import datetime

from dateutil.relativedelta import relativedelta
from django import forms
from supervision.models import CheckMonth, OversightPeriod
from documents.models import Checklist, Prescription, PKD, Approval, Elimination, Report, Notification, Moved


class ChecklistForm(forms.ModelForm):
    month = forms.IntegerField(required=False)
    area = forms.IntegerField(required=False)

    class Meta:
        model = Checklist
        fields = ['month', 'files', 'comment']
        widgets = {
            'files': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }


class CheckMonthForm(forms.ModelForm):
    class Meta:
        model = CheckMonth
        fields = ['checking']
        widgets = {
            'checking': forms.CheckboxInput(attrs={'class': 'absol'})
        }


class PrescriptionForm(forms.ModelForm):

    class Meta:
        model = Prescription
        fields = ['letter', 'fine_protocol']
        widgets = {
            'letter': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'fine_protocol': forms.ClearableFileInput(attrs={'class': 'form-control'})
        }


class PKDForm(forms.ModelForm):

    class Meta:
        model = PKD
        fields = ['letter', 'pkd']
        widgets = {
            'letter': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'pkd': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }


class ApprovalForm(forms.ModelForm):

    class Meta:
        model = Approval
        fields = ['approval', 'deadline']
        widgets = {
            'approval': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'deadline': forms.DateInput(
                                format=('%Y-%m-%d'),
                                attrs={'class': 'form-control',
                                       'type': 'date'
                                      }),
        }


class EliminationForm(forms.ModelForm):

    class Meta:
        model = Elimination
        fields = ['letter']
        widgets = {
            'letter': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }


class ReportForm(forms.ModelForm):

    class Meta:
        model = Report
        fields = ['report']
        widgets = {
            'report': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }


class NotificationForm(forms.ModelForm):

    class Meta:
        model = Notification
        fields = ['letter']
        widgets = {
            'letter': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }


class MovedForm(forms.ModelForm):
    class Meta:
        model = Moved
        fields = ['raport']
        widgets = {
            'raport': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }


class OversightPeriodForm(forms.ModelForm):
    current = datetime.today().date()
    start = forms.DateField(
        widget=forms.SelectDateWidget(
            years=range(current.year, current.year + 10)
        )
    )

    class Meta:
        model = OversightPeriod
        fields = ['start']

    def __init__(self, *args, **kwargs):
        super(OversightPeriodForm, self).__init__(*args, **kwargs)
        self.fields['start'].initial = datetime.today().date()

supervision/views.py
import json
from dateutil.relativedelta import relativedelta
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from documents.views import get_checklist
from products.models import Company
from supervision.forms import CheckMonthForm, OversightPeriodForm
from supervision.models import CheckArea, CheckMonth, Permission, OversightPeriod
from documents.models import Checklist
from django.http import JsonResponse, HttpResponseNotFound
from datetime import datetime, timedelta
import locale
import calendar
from django.contrib.auth.decorators import user_passes_test
from supervision.tasks import check_deadline, check_expiry
from users.views import is_superuser
locale.setlocale(locale.LC_TIME, 'ru_RU.UTF-8')

russian_month_names = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь']
   

def table_date(date):
    start_date = date.start
    end_date = date.end
    current_date = start_date
    months = []
    years = {}

    while current_date <= end_date:
        months.append(russian_month_names[current_date.month - 1].capitalize())
        if current_date.year in years:
            years[current_date.year] += 1
        else:
            years[current_date.year] = 1
        current_date += timedelta(days=31)

    table_html = "<tr>\n"

    for year, m in years.items():
        table_html += f'    <th colspan="{m}" class="text-center">{year}</th>\n'
    table_html += "</tr>\n"
    table_html += "<tr>\n"

    for month in months:
        table_html += f'    <td><div class="ops_td text-center">{month}</div></td>\n'
    table_html += "</tr>\n"
    return table_html


@login_required
def control(request, company_slug, edit=False):
    if 'period' in request.GET:
        period = request.GET['period']
        try:
            date = OversightPeriod.objects.get(company__slug=company_slug, period=period)
        except OversightPeriod.DoesNotExist:
            date = None
    else:
        try:
            date = OversightPeriod.objects.filter(company__slug=company_slug).first()
        except OversightPeriod.DoesNotExist:
            date = None
    if date is None:
        context = {
            'check_areas': None,
            'company_slug': company_slug,
            'period_form': OversightPeriodForm()
        }
        return render(request, 'supervision/check_area_table.html', context)
    table_html = table_date(date)
    check = []
    check_areas = None
    if request.user.is_superuser or request.user.groups.all().first().name == 'avia':
        check_areas = CheckArea.objects.filter(company__slug=company_slug).order_by('id')
    elif request.user.groups.all().first().name == 'ins':
        check_areas = Permission.objects.filter(area__company__slug=company_slug, user=request.user,
                                                access=True).order_by('id')
        if not check_areas.exists():
            return HttpResponseNotFound('<div style="display:flex;width:100vw; margin-top: 30vh;">'
                                        '   <h1 style="margin:auto;">Page Does Not Exist...</h1>'
                                        '</div>')
    for check_area in check_areas:

        months = {}
        for i in range(1, 21):
            check_month = None
            if request.user.is_superuser or request.user.groups.all().first().name == 'avia' :
                try:
                    check_month = CheckMonth.objects.get(area=check_area, month=i)
                except CheckMonth.DoesNotExist:
                    check_month = {
                        'key': i,
                        'month': None
                    }
            elif request.user.groups.all().first().name == 'ins':
                try:
                    check_month = CheckMonth.objects.get(area=check_area.area, month=i)
                except CheckMonth.DoesNotExist:
                    check_month = {
                        'key': i,
                        'month': None
                    }
            months[i] = check_month
        if request.user.is_superuser or request.user.groups.all().first().name == 'avia':
            check.append((check_area, months))
        else:
            check.append((check_area.area, months))

    context = {
        'range': range(1, 21),
        'check_areas': check,
        'table_html': table_html,
        'edit': edit,
        'company_slug': company_slug,
        'periods': OversightPeriod.objects.filter(company__slug=company_slug)
    }
    return render(request, 'supervision/check_area_table.html', context)


@login_required
def dashboard(request, company_slug):
    select = None
    areas = CheckArea.objects.filter(company__slug=company_slug)
    if 'select' in request.GET:
        select = int(request.GET['select'])
        if select != 0:
            areas = CheckArea.objects.filter(company__slug=company_slug, id=select)

    not_checked = 0
    checked = 0
    checking = 0
    out_check = 0
    comments = {}
    for area in areas:
        months = CheckMonth.objects.filter(area=area)
        for month in months:
            if month.checking:
                try:
                    checklist = Checklist.objects.get(area=area, month=month, original=None)
                    if checklist.comment:
                        checking += 1
                        comments.update({area.title: month})
                    else:
                        checked += 1

                except Checklist.DoesNotExist:
                    not_checked += 1
            else:
                out_check += 1

    areas = CheckArea.objects.filter(company__slug=company_slug)

    data = [
        {'category': 'Без предписаний', 'percentage': checked},
        {'category': 'Предписание', 'percentage': checking},
        {'category': 'Еще не проверено', 'percentage': not_checked},
    ]

    context = {
        'company_slug': company_slug,
        'data': json.dumps(data),
        'areas': areas,
        'select': select,
        'comments': comments,
        'all_month': not_checked + checked + checking #+ out_check
    }
    return render(request, 'supervision/dashboard.html', context)


@user_passes_test(is_superuser)
def delete_check_month(request, month_id):
    if request.method == 'POST':
        check_month = CheckMonth.objects.get(id=month_id)
        area_id = check_month.area.pk
        month = check_month.month
        check_month.delete()
        return JsonResponse({'url': f'/oversight/api/{area_id}/{month}/add/'})
    return JsonResponse({})


@user_passes_test(is_superuser)
def add_check_month(request, month_id, area_id):
    if request.method == 'POST':                
        check_month = CheckMonth(
            area_id=area_id,
            month=month_id,
        )
        check_month.checking = True
        check_month.save()
        check_deadline()
        check_expiry()
        return JsonResponse({'url': f'/oversight/api/{check_month.pk}/delete/'})
    return JsonResponse({})


count: int = 1


def supervise(request, company_slug):
    global count
    count = 1
    if request.user.is_superuser:
        groups = 'admin'
    else:
        groups = request.user.groups.all().first().name
    area = int(request.GET['area'])
    month = int(request.GET['month'])
    try:
        ch_area = CheckMonth.objects.get(month=month, area__id=area)
        if ch_area.checking:
            context, _ = get_checklist(0, area, month)
            perm = Permission.objects.filter(user=request.user)
            return render(request, 'supervision/supervise.html', {
                'group': groups,
                'context': context,
                'area': area,
                'month': month,
                'company_slug': company_slug,
                'perm': perm,
                'title': 'Проверка'
            })
        else:
            return HttpResponseNotFound('<div style="display:flex;width:100vw; margin-top: 30vh;">'
                                        '   <h1 style="margin:auto;">Page Does Not Exist...</h1>'
                                        '</div>')
    except CheckMonth.DoesNotExist:
        return HttpResponseNotFound('<div style="display:flex;width:100vw; margin-top: 30vh;">'
                                    '<h1 style="margin:auto;">Page Does Not Exist...</h1>'
                                    '</div>')


def create_period(request, company_slug):
    if request.method == 'POST':
        form = OversightPeriodForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data['start']
            start_date = start_date.replace(day=1)
            end_date = start_date + relativedelta(months=+19)
            company = Company.objects.get(slug=company_slug)
            period = f'{start_date.year}-{end_date.year}'

            oversight_period = OversightPeriod.objects.create(
                start=start_date,
                end=end_date,
                company=company,
                period=period
            )
            oversight_period.save()

            return redirect('supervision:control', company_slug=company_slug)
        

@user_passes_test(is_superuser)
def move_check(request, area_id):
    area = CheckArea.objects.get(id=int(area_id))
    checkmonths = CheckMonth.objects.filter(area_id=int(area_id))
    serialized_months = []
    current_date = datetime.now().date() 
    for mon in range(1, 21):
        checkmonth = None
        try:
            checkmonth = checkmonths.get(month=mon)
        except CheckMonth.DoesNotExist:
            pass
        if checkmonth:
            serialized_months.append({

supervision/templates/supervision/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Статистика</title><link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;400&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<style>
    body {
  height: 90vh
}
    .chart-container {
        position: relative;
        display: flex;
        margin-right: 800px;
        width: 810px;
        height: 400px;
    }
        .nav-tabs .nav-link:hover{
            border: 1px solid #0a4275;
        }
        .nav-tabs .active:hover{
            border-bottom: 1px solid transparent;
        }
        .empty{
            display: flex;
            flex-direction: column;
            margin: auto 0;
        }
        .empty img,.empty h1{
            margin: 0 auto;
            color: #1073dc;
            font-weight: lighter;
            font-family: 'Comfortaa', sans-serif;
        }
</style>
</head>
<body>
<ul class="nav nav-tabs pt-3" style="border-bottom: 1px solid #0a4275">
  <li class="nav-item">
    <a style="color: #0a4275;" class="nav-link" href="{% url 'index' %}">Главная</a>
  </li>
  <li class="nav-item">
    <a  style="color: #0a4275;" class="nav-link" href="{% url 'supervision:control' company_slug=company_slug %}">Надзор</a>
  </li>
    <li>
    <a style="
            background-color: white;
            color: #0a4275;
            border-top: 1px solid #0a4275;
            border-right: 1px solid #0a4275;
            border-left: 1px solid #0a4275;
" class="nav-link active" aria-current="page"  href="#">Статистика</a>
  </li>
</ul>
{% if all_month != 0 %}
<form method="get" class="form container my-4 input-group">
    <label id="for-select" class="input-group-text">Выберите область</label>
    <select aria-describedby="for-select" onchange="this.form.submit()" class="form-select col-10" aria-label="Default select example" name="select">
    {% if select == None %}
      <option selected>Все области проверки</option>
        {% for area in areas %}
            <option value="{{ area.pk }}">{{ area.title }}</option>
        {% endfor %}
    {% else %}
        <option value="0">Все области проверки</option>

        {% for area in areas %}
            {% if select == area.pk %}
            <option selected value="{{ area.pk }}">{{ area.title }}</option>
            {% else %}
            <option value="{{ area.pk }}">{{ area.title }}</option>
            {% endif %}
        {% endfor %}
    {% endif %}
    </select>
</form>

<div class="chart-container px-4">
    <canvas id="barChart" width="600px"></canvas>
    <canvas id="pieChart" width="600px"></canvas>
</div>
{% if comments|length != 0 %}
<div class="container pt-5">
    <h5>Предписания:</h5>
    <ol class="list">
        {% for title, comment in comments.items %}
            <li>
            <a class="icon-link icon-link-hover" style="--bs-link-hover-color-rgb: 25, 135, 84;"
               href="{% url 'supervision:check_area_table' company_slug=company_slug %}?area={{ comment.area.pk }}&month={{ comment.month }}">
                {{ comment.area.title }} в {{ comment.get_month_title }} месяце {{ comment.date.year }}
            </a>
            </li>
        {% endfor %}
    </ol>
</div>
{% endif %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>


const ctx = document.getElementById('pieChart').getContext('2d');
const ctx2 = document.getElementById('barChart').getContext('2d');
const data = JSON.parse('{{ data|escapejs }}');

const labels = data.map(function(item) {
            return item.category + ' (' + ((item.percentage * 100) / {{all_month}}).toFixed(3) + '%)';
        });
const labels_bar = data.map(function(item) {
            return item.category
        });
const values = data.map(function(item) {
    let perc = ((item.percentage * 100) / {{all_month}})
    return perc
});

const config = {
    type: 'pie',
    data: {
        labels: labels,
        datasets: [{
            data: values,
            backgroundColor: [
                'rgba(6,211,26, 0.5)',
                'rgba(255, 99, 132, 0.5)',
                 'rgba(6,199,243,0.5)',
                'rgba(124,124,124,0.33)',
            ],
            borderColor: [
                'rgba(6,211,26, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(6,199,243,1)',
                'rgba(75,75,75,0.5)',
            ],
            borderWidth: 1
        }]
    },
    options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
            legend: {
              position: "right",
              align: "middle"
          }
        }

    }
};
const config2 = {
    type: 'bar',
    data: {
        labels: labels_bar,
        datasets: [{
            data: values,
            backgroundColor: [
                'rgba(6,211,26, 0.5)',
                'rgba(255, 99, 132, 0.5)',
                'rgba(0,208,255,0.5)',
                'rgba(124,124,124,0.3)',
            ],
            borderColor: [
                'rgba(6,211,26, 0.9)',
                'rgba(255, 99, 132, 1)',
                'rgba(6,199,243,1)',
                'rgba(75,75,75,0.5)',
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
              beginAtZero: true
            }
          },
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
            legend: {
                display: false  // Hide the legend
            }
        }
    }
}

const pieChart = new Chart(ctx, config);
const barChart = new Chart(ctx2, config2);
</script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
{% else %}
    {% load static %}
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="empty" style="opacity: 0.2">
        <img src="{% static 'blue_paper_plane.png' %}" alt="empty" height="300">
        <h1>Пусто</h1>
    </div>
    </div>
{% endif %}
</body>
</html>

supervision/templates/supervision/moved.html
{% extends 'products/base.html' %}


{% block css %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <style>
    </style>
{% endblock %}


{% block content %}

    <div style="position: relative" class="pt-5 mt-5 px-2" >
        <a class="btn btn-outline-secondary" style="font-size: 14px;" href="{% url 'supervision:control' company_slug=company_slug %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left mr-1" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
        </svg>Назад</a>
    </div>
<div class="container-sm" style="height: max-content">
    <div class="text-center">
        <table class="table text-left">
          <thead>
            <tr>
              <th scope="col" class="text-center">#</th>
              <th scope="col" >Название документа</th>
              <th scope="col">Статус</th>
            </tr>
          </thead>
          <tbody id="supervise">
          {% if not exists %}

                <tr>
                    <td class="col-1 text-center">1</td>
                    <td class="col-8">
                        <h5>
                            Рапорт
                        </h5>

                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#raportModal">
                        Загрузить файлы
                    </button>
                    <script>
                    document.body.insertAdjacentHTML('beforeend', '<div class="modal" tabindex="-1" id="raportModal" aria-labelledby="raportModalLabel" aria-hidden="true">' +
                        '      <div class="modal-dialog" id="prId">' +
                        `          <form onsubmit="postDocument.disabled = true; return true;" method="post" enctype="multipart/form-data" class="modal-content" action="{% url 'supervision:post' %}?area={{ area }}&month={{ month }}&saveto={{ form.saveto }}&company={{ company_slug }}">
                                        <div class="modal-header">
                                            <h5 class="form-label">Заполните все поля</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            {% csrf_token %}
                                            <div class="mb-3 col-12">
                                                 <label class="form-label">Рапорт</label>
                                                 {{ form.raport }}
                                            </div>
                                    </div>
                                   <div class="modal-footer">
                                       <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                       <button id="postDocument" type="submit" class="btn btn-dark">Отправить</button>
                                    </div>
                                    </form>` +
                        '       </div>' +
                        '    </div>')
                    </script>

                    </td>
                    <td class="col-3">

                    </td>

                </tr>
          {% else %}
              <tr>
                    <td class="col-1 text-center">1</td>
                    <td class="col-8">
                        <h5>
                            Рапорт
                        </h5>
                        <div class="col-12">
                                <a href="{{ raport.raport.url }}" class="text-primary"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-pdf mb-1" viewBox="0 0 16 16">
                                                    <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"></path>
                                                    <path d="M4.603 14.087a.81.81 0 0 1-.438-.42c-.195-.388-.13-.776.08-1.102.198-.307.526-.568.897-.787a7.68 7.68 0 0 1 1.482-.645 19.697 19.697 0 0 0 1.062-2.227 7.269 7.269 0 0 1-.43-1.295c-.086-.4-.119-.796-.046-1.136.075-.354.274-.672.65-.823.192-.077.4-.12.602-.077a.7.7 0 0 1 .477.365c.088.164.12.356.127.538.007.188-.012.396-.047.614-.084.51-.27 1.134-.52 1.794a10.954 10.954 0 0 0 .98 1.686 5.753 5.753 0 0 1 1.334.05c.364.066.734.195.96.465.12.144.193.32.2.518.007.192-.047.382-.138.563a1.04 1.04 0 0 1-.354.416.856.856 0 0 1-.51.138c-.331-.014-.654-.196-.933-.417a5.712 5.712 0 0 1-.911-.95 11.651 11.651 0 0 0-1.997.406 11.307 11.307 0 0 1-1.02 1.51c-.292.35-.609.656-.927.787a.793.793 0 0 1-.58.029zm1.379-1.901c-.166.076-.32.156-.459.238-.328.194-.541.383-.647.547-.094.145-.096.25-.04.361.01.022.02.036.026.044a.266.266 0 0 0 .035-.012c.137-.056.355-.235.635-.572a8.18 8.18 0 0 0 .45-.606zm1.64-1.33a12.71 12.71 0 0 1 1.01-.193 11.744 11.744 0 0 1-.51-.858 20.801 20.801 0 0 1-.5 1.05zm2.446.45c.15.163.296.3.435.41.24.19.407.253.498.256a.107.107 0 0 0 .07-.015.307.307 0 0 0 .094-.125.436.436 0 0 0 .059-.2.095.095 0 0 0-.026-.063c-.052-.062-.2-.152-.518-.209a3.876 3.876 0 0 0-.612-.053zM8.078 7.8a6.7 6.7 0 0 0 .2-.828c.031-.188.043-.343.038-.465a.613.613 0 0 0-.032-.198.517.517 0 0 0-.145.04c-.087.035-.158.106-.196.283-.04.192-.03.469.046.822.024.111.054.227.09.346z"></path>
                                                </svg>
                                    Файл
                                </a>
                        </div>

                    </td>
                    <td class="col-3">
                    </td>
                </tr>
          {% endif %}
          </tbody>
        </table>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}