aviaServer/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from products.views import index
from django.urls import path, include

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', index, name='index'),
    path('', include('products.urls', namespace='products')),
    path('oversight/', include('supervision.urls', namespace='supervision')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


products/urls.py
from products.views import index
from .views import  companies_list, create_company, edit_company
from django.urls import path

app_name = 'products'
urlpatterns = [
    path('', index, name='index'),
    path('companies/', companies_list, name='companies_list'),
    path('companies/add', create_company, name='register_avia'),
    path('companies/<slug:company_slug>/', edit_company, name='edit_company'),
]

users/urls.py
from users.views import register, login, profile, forgot_password, logout, user_list, grant_access, update_perm, delete_user, delete_company, edit_user, point
from django.urls import path

app_name = 'users'
urlpatterns = [
    path('', user_list, name='user_list'),
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('restore-password/', forgot_password, name='password'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('api/<slug:user_slug>/update-permission', update_perm, name='update_perm'),
    path('<slug:user_slug>/', edit_user, name='edit_user'),
    path('<slug:user_slug>/update-permission/', point, name='permission'),
    path('<slug:user_slug>/delete', delete_user, name='delete_user'),
    path('<slug:company_slug>/delete', delete_company, name='delete_company'),
    path('<slug:user_slug>/grant_access/', grant_access, name='grant_access'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    image = models.ImageField(upload_to='user_img', blank=True)

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User
from products.models import Company
from django import forms


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-1'


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'image')

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        for field_name, filed in self.fields.items():
            if field_name != 'image':
                filed.widget.attrs['class'] = 'form-control py-1'
            else:
                filed.widget.attrs['class'] = 'form-control'


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly': True}))
    email = forms.CharField(widget=forms.EmailInput())
    image = forms.ImageField(required=False) 

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'image')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for _, filed in self.fields.items():
            filed.widget.attrs['class'] = 'form-control py-1'
        self.fields['image'].widget.attrs['class'] = 'custom-file-input'
        



users/views.py
import json
from django.contrib import auth, messages
from django.http import JsonResponse
from django.shortcuts import render, HttpResponseRedirect, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import user_passes_test
from products.models import Company
from supervision.models import Permission, CheckArea
from supervision.tasks import check_deadline, check_expiry
from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from users.models import User
from django.core.mail import send_mail
from django.utils.translation import gettext as _
from decouple import config



def is_superuser(user):
    return user.is_superuser


# Create your views here.
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))

    else:
        form = UserLoginForm
    context = {
        'form': form,
        'title': 'Авторизация'
    }
    return render(request, 'users/login.html', context)


@user_passes_test(is_superuser)
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            instance = form.save()
            group = Group.objects.get(name='ins')
            instance.groups.add(group)
            instance.save()
            return HttpResponseRedirect(reverse('users:user_list'))
    else:
        form = UserRegistrationForm()
    context = {
        'form': form,
        'title': 'Регистрация'
    }
    return render(request, 'users/register_inspector.html', context)

@user_passes_test(is_superuser)
def edit_user(request, user_slug):
    user = User.objects.get(username=user_slug)
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, files=request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:user_list'))
    else:
        form = UserProfileForm(instance=user)
    context = {
        'form': form,
        'edit': True,
        'inspector': user,
        'title': 'Изменить данные'
    }
    return render(request, 'users/register_inspector.html', context)


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, files=request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)
    context = {
        'form': form,
        'title': 'Информация'
    }
    return render(request, 'users/profile.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


@user_passes_test(is_superuser)
def user_list(request): 
    perms = Permission.objects.all()
    inspectors_group = get_object_or_404(Group, name='ins')
    users = inspectors_group.user_set.all()
    context = {
        'users': users,
        'perms': perms,
        'title': 'Инспекторы'
    }
    return render(request, 'users/user_list.html', context)




@user_passes_test(is_superuser)
def point(request, user_slug):
    from users.models import User
    user = User.objects.get(username=user_slug)
    permissions = None
    if user.groups.all().first().name == 'ins':
        permissions = Permission.objects.filter(user=user).order_by('id')
    companies = Company.objects.all()
    company_list = {}
    for company in companies:
        has = False
        areas = {}
        if permissions:
            check_areas = CheckArea.objects.filter(company=company)
            for ch in check_areas:
                for per in permissions:
                    if company == per.area.company:
                        areas.update({
                            per.area: {
                             'area': per.area,
                             'perm': per.access
                            }
                        })
                        has = True
            company_list.update({
                company.name: {
                    'company': company,
                    'perm': has,
                    'areas': areas
                }
            })
        else:
            company_list.update({
                company.name: {
                    'company': company,
                    'perm': has,
                }
            })

    context = {
        'companies': company_list,
        'inspector': user,
        'title': 'Доступ'
    }
    return render(request, 'users/point.html', context)


@user_passes_test(is_superuser)
def grant_access(request, user_slug):
    if request.method == 'POST':
        company_id = int(request.POST['company_id'])
        if Permission.objects.filter(area__company__id=company_id, user__username=user_slug).exists():
            perm = Permission.objects.filter(area__company__id=company_id, user__username=user_slug)
            perm.delete()
        else:
            from users.models import User
            user = User.objects.get(username=user_slug)
            areas = CheckArea.objects.filter(company__id=company_id)
            for area in areas:
                perm = Permission(area=area, user=user)
                perm.save()
            check_deadline()
            check_expiry()
        return redirect('users:permission', user_slug=user_slug)
    else:
        return JsonResponse({'message': 'Недопустимый запрос.'}, status=400)


@user_passes_test(is_superuser)
def update_perm(request, user_slug):
    if request.method == 'POST':
        body_unicode = request.body.decode('utf-8')
        body_data = json.loads(body_unicode)
        area_id = body_data.get('area_id')
        perm = Permission.objects.get(area__id=area_id, user__username=user_slug)
        perm.access = not perm.access
        perm.save()
        if perm.access:
            return JsonResponse({'message': True})
        else:
            return JsonResponse({'message': False})
    else:
        return JsonResponse({'message': 'Недопустимый запрос.'}, status=400)


@user_passes_test(is_superuser)
def delete_user(request, user_slug):
    try:
        user = User.objects.get(username=user_slug)
        user.delete()
    except User.DoesNotExist:
        pass
    return redirect('users:user_list')


def forgot_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        user = User.objects.filter(email=email).first()
        if user:
            password = user.password 
            print('sending')
            send_mail(
                _('Your Password'),  
                _('Your password is: ') + password,  
                config('EMAIL_HOST_USER'),  
                [email],
            )
            print('sent')
            return render(request, 'users/login.html')
        else:
            return render(request, 'users/forgot_password.html')
    else:
        return render(request, 'users/forgot_password.html')


@user_passes_test(is_superuser)
def delete_company(request, company_slug):
    try:
        company = Company.objects.get(slug=company_slug)
        company.delete()
    except Company.DoesNotExist:
        pass
    return redirect('users:companies_list')

users/templates/users/forgot_password.html
{% extends 'products/base.html' %}
{% load static %}


{% block content  %}

<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container mt-5">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if messages or errors %}
                        <div class="alert
                        {% if messages %} alert-success {% else %} alert-warning {% endif %} alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {% if messages %}
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            {% endif %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h5 class="text-center font-weight-light my-4">Ваш пароль будет отправлен на вашу электронную почту</h5>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:password' %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="small mb-1" for="id_email">Почта</label>
                                        <input type="email" name="email" placeholder="Введите электронную почту" maxlength="150" class="form-control py-1" required="" id="id_email">
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <input class="btn btn-primary" type="submit" value="Отправить">
                                    </div>
                                </form>
                            </div>
                            <!-- <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'products/base.html' %}
{% load static %}


{% block content  %}

<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container mt-5">
                <div class="row justify-content-center">
                    <div class="col-lg-5">
                        {% if messages or form.errors %}
                        <div class="alert
                        {% if messages %} alert-success {% else %} alert-warning {% endif %} alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {% if messages %}
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            {% else %}
                                {{ form.non_field_errors }}
                            {% endif %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                            </div>
                            <div class="card-body">
                                <form action="{% url 'users:login' %}" method="post">
                                    {% csrf_token %}
<!--                                    {{ form.as_p }}-->
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                        {{ form.username }}
                                    </div>
                                    <div class="form-group">
                                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                        {{ form.password }}
                                    </div>
                                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                        <a class="small" href="{% url 'users:password' %}">Забыли пароль?</a>
                                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                    </div>
                                </form>
                            </div>
                            <!-- <div class="card-footer text-center">
                                <div class="small"><a href="{% url 'users:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
            <div class="col-lg-12 text-center">
                <img width="100" height="100"
                     src="{% if request.user.image %} {{ request.user.image.url }} {% else %} {% static 'vendor/img/users/avatar.png' %} {% endif %}"
                     class="img-thumbnail"
                     id="img-thumbnail"
                     >
            </div>
            <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            <div id="container-image" style="{% if user.image %}display: none {% endif %}">
                            {{ form.image }}
                            </div>
                            <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script >
    const inputImage = document.getElementById('id_image')
    const image = document.getElementById('img-thumbnail')
    inputImage.onchange = (e) => {
        image.src = URL.createObjectURL(e.target.files[0])
    }

</script>
{% endblock %}

users/templates/users/user_list.html
{% extends 'products/base.html' %}
{% block css %}
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }


        .table-container {
            margin: 20px;
            overflow-x: auto;
        }


        .row.head {
            padding: 12px 15px;
            background-color: #0a4275;
            color: white;
        }
        .row{
            align-items: center;
            padding: 6px 0;
        }
        

        .row:not(.head):hover {
            background-color: rgba(10, 66, 117, 0.3);
        }

        .user_label th {

            padding: 12px 15px;
            background-color: rgba(10, 66, 117, 0.68);
        }
        .row{
            border-top: none;
            border-bottom:  1px solid #0a4275;
            border-left:  1px solid #0a4275;
            border-right:  1px solid #0a4275;
        }

        .dropdown-center button, .row .btn {
            border-color: #0a4275 !important;
            color: #0a4275 !important;
        }

        .dropdown-center button:hover,
        .row .btn:hover {
            border-color: #0a4275 !important;
            background-color: #0a4275 !important;
            color: white !important;
        }
        .user-list{
            width: 100%;
        }
        .row{
            width: 100%;
            margin-left: auto;
            margin-right: auto;
        }
        @media screen and (max-width: 768px) {
            .user-list .col-hide{
                display: none;
            }
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container mt-5" style="padding-top: 70px">
{% if title == 'Компании' %}
        <h3>Список авиакомпании</h3>
{% else %}
	<h3>Список инспекторов</h3>
{% endif %}
        <div class="user-list">
            <div class="row head">
                {% if title == 'Компании' %}
                <div class="col-5 col-md-7 px-0">
                    <h5>Название</h5>
                </div>
                <div class="col-5 col-md-3">
                    <h5>Почта</h5>
                </div>
                <div class="col-2"></div>
                {% else %}
                <div class="col-md-4 col-4">
                    <h5>ФИО</h5>
                </div>
                <div class="col-3 col-hide">
                    <h5>Почта</h5>
                </div>
                <div class="col-md-2 col-3"></div>
                <div class="col-2 col-md-1"></div>
                {% endif %}
            </div>

            {% if title == 'Компании' %}
                {% for company in companies %}
                    <div class="row">
                        <div class="col-5 col-md-7">
                            <a href="{% url 'products:edit_company' company_slug=company.slug %}?">{{ company.name }}</a>
                        </div>
                        <div class="col-5 col-md-3"><p>{{ company.email }}</p></div>
                        <div class="col-2">
                            <a href="{% url 'users:delete_company' company_slug=company.slug %}"  onclick="event.target.disabled = true; return true;">
                                <button class="btn btn-outline-primary" style="padding: 5px 10px" type="button">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                    </svg>
                                </button>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                {% for inspector in users %}
                    <div class="row">
                        <div class="col-md-4 col-5">
                            <a href="{% url 'users:edit_user' user_slug=inspector.username %}" style="text-transform: capitalize;">{{ inspector.first_name }} {{inspector.last_name}}</a>
                        </div>
                        <div class="col-4 col-hide">{{ inspector.email }}</div>
                        <div class="col-md-3 col-5">
                            <a href="{% url 'users:permission' user_slug=inspector.username %}">Изменить доступ</a>
                        </div>
                        <div class="col-2 col-md-1">
                            <a href="{% url 'users:delete_user' user_slug=inspector.username %}" onclick="event.target.disabled = true; return true;">
                                <button class="btn btn-outline-primary" style="padding: 5px 10px" type="button">
                                 <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                    </svg>
                                </button>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="dropdown-center my-3">
            {% if title == 'Компании' %}
                <a class="text-black-50" href="{% url 'products:register_avia' %}">
                    <button class="btn btn-outline-primary px-3" style="padding: 6px 5px" type="button">
                        Добавить компанию
                    </button>
                </a>
            {% else %}
                <a class="text-black-50" href="{% url 'users:register' %}">
                    <button class="btn btn-outline-primary px-3" style="padding: 6px 5px" type="button">
                        Добавить инспектора
                    </button>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}