aviaServer/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from products.views import index
from django.urls import path, include

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', index, name='index'),
    path('', include('products.urls', namespace='products')),
    path('oversight/', include('supervision.urls', namespace='supervision')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


products/urls.py
from products.views import index
from .views import  companies_list, create_company, edit_company
from django.urls import path

app_name = 'products'
urlpatterns = [
    path('', index, name='index'),
    path('companies/', companies_list, name='companies_list'),
    path('companies/add', create_company, name='register_avia'),
    path('companies/<slug:company_slug>/', edit_company, name='edit_company'),
]

supervision/urls.py
from django.urls import path
from supervision.views import control, supervise, delete_check_month, add_check_month, dashboard, create_period, move_check
from documents.views import  update_move_check, get_moved, post

app_name = "supervision"

urlpatterns = [
    path('<slug:company_slug>/', control, name='control'),
    path('<slug:company_slug>/edit', control, {'edit': True}, name='edit'),
    path('<slug:company_slug>/dashboard/', dashboard, name='dashboard'),
    path('<slug:company_slug>/check-area-table/', supervise, name='check_area_table'),
    path('<slug:company_slug>/moved/', get_moved, name='moved'),
    path('<slug:company_slug>/add-period/', create_period, name='period'),
    path('api/post', post, name='post'),
    path('api/<int:month_id>/delete/', delete_check_month, name='delete_check_month'),
    path('api/<int:area_id>/<int:month_id>/add/', add_check_month, name='add_check_month'),
    path('api/move-check/<int:area_id>/', move_check, name='move'),
    path('api/post-move-check/<slug:company_slug>/', update_move_check, name='update_move'),

]

users/urls.py
from users.views import register, login, profile, forgot_password, logout, user_list, grant_access, update_perm, delete_user, delete_company, edit_user, point
from django.urls import path

app_name = 'users'
urlpatterns = [
    path('', user_list, name='user_list'),
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('restore-password/', forgot_password, name='password'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('api/<slug:user_slug>/update-permission', update_perm, name='update_perm'),
    path('<slug:user_slug>/', edit_user, name='edit_user'),
    path('<slug:user_slug>/update-permission/', point, name='permission'),
    path('<slug:user_slug>/delete', delete_user, name='delete_user'),
    path('<slug:company_slug>/delete', delete_company, name='delete_company'),
    path('<slug:user_slug>/grant_access/', grant_access, name='grant_access'),

]

products/models.py
from django.db import models
from django.utils.text import slugify
from users.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class KindOfActivity(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Виды деятельности'
        verbose_name = 'Вид деятельности'


class Company(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='Название авиакомпании/Управленческий персонал')
    number = models.IntegerField(verbose_name="Номер СЭ")
    code = models.CharField(max_length=6, unique=True, verbose_name='3-буквен КОД ИКАО')
    validity = models.DateField(verbose_name="Срок действия сертификата эксплуатанта (СЭ)")
    status = models.BooleanField(default=True, verbose_name='Статус СЭ')
    address = models.CharField(max_length=256, unique=True, verbose_name='Адрес')
    first_phone = models.CharField(max_length=20, unique=True, verbose_name='1-номер телефона')
    second_phone = models.CharField(max_length=20, unique=True, blank=True, default=" ", verbose_name='2-номер телефона')
    email = models.CharField(max_length=64, unique=True, verbose_name='Эл. почта')
    kind_of_activity = models.ForeignKey(KindOfActivity, on_delete=models.CASCADE, verbose_name='Вид деятельности')
    slug = models.SlugField(unique=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Как пользователь')
    password = models.CharField(max_length=255, verbose_name='Пароль')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = "Компании"


@receiver(post_save, sender=Company)
def create_user(sender, instance, created, **kwargs):
    from django.contrib.auth.models import Group
    if created and not instance.user:
        user = User.objects.create_user(username=instance.slug, password=instance.password)
        user.name = instance.name
        user.email = instance.email
        group = Group.objects.get(name='avia')
        user.groups.add(group)
        user.is_active = True
        user.save()
        instance.user = user
        instance.save()

products/forms.py
# forms.py
from django import forms
from .models import Company


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['name', 'number', 'code', 'validity', 'status', 'address', 'first_phone', 'second_phone', 'email', 'kind_of_activity', 'password', 'slug']
        widgets = {
            'password': forms.PasswordInput(attrs={'placeholder': 'Введите пароль'}),
            'first_phone': forms.NumberInput(attrs={'placeholder': 'Введите первый номер телефона'}),
            'second_phone': forms.NumberInput(attrs={'placeholder': 'Введите второй номер телефона'}),
            'validity': forms.DateInput(attrs={'placeholder': 'ГГГГ-ММ-ДД'}),
        }
        labels = {
            'name': 'Название компании',
            'number': 'Номер СЭ',
            'code': '3-буквен КОД ИКАО',
            'validity': 'Действительно до',
            'status': 'Статус СЭ',
            'address': 'Адрес компании',
            'first_phone': 'Первый номер телефона',
            'second_phone': 'Второй номер телефона',
            'email': 'Электронная почта',
            'kind_of_activity': 'Вид деятельности',
            'password': 'Пароль',
            'slug': 'Username'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Введите название компании'
        self.fields['number'].widget.attrs['placeholder'] = 'Введите номер'
        self.fields['code'].widget.attrs['placeholder'] = 'Введите код'
        self.fields['address'].widget.attrs['placeholder'] = 'Введите адрес'
        self.fields['first_phone'].widget.attrs['placeholder'] = 'Введите первый номер телефона'
        self.fields['second_phone'].widget.attrs['placeholder'] = 'Введите второй номер телефона'
        self.fields['email'].widget.attrs['placeholder'] = 'Введите адрес эл.почты'
        self.fields['slug'].widget.attrs['readonly'] = True
        for field_name, filed in self.fields.items():
            if field_name != 'status':
                filed.widget.attrs['class'] = 'form-control py-2'
                
        instance = getattr(self, 'instance', None)
        if instance and instance.pk: 
            self.fields['password'].required = False
            self.fields['slug'].required = False
        else:
            self.fields['slug'].required = False
            self.fields['slug'].widget.attrs['hidden']= True
            self.fields['slug'].label = ''
                
    def clean(self):
        cleaned_data = super().clean()
        instance = getattr(self, 'instance', None)

        if instance and instance.pk:
            if 'password' not in self.cleaned_data:
                cleaned_data['password'] = instance.password
            if 'slug' not in self.cleaned_data:
                cleaned_data['slug'] = instance.slug
        return cleaned_data

products/views.py
#views.py
from datetime import datetime
from django.shortcuts import render, get_object_or_404, redirect
from products.models import KindOfActivity, Company
from products.forms import CompanyForm
from supervision.models import Permission
from django.contrib.auth.decorators import user_passes_test


def is_superuser(user):
    return user.is_superuser


def index(request):
    context = None
    if request.user.is_authenticated:
        if request.user.is_superuser:
            companies = Company.objects.all()
            for company in companies:
                company.time_difference = company.validity - datetime.today().date()
            context = {
                'activities': KindOfActivity.objects.all(),
                'companies': companies,
                'title': 'Главная'
            }
        elif request.user.groups.all().first().name == 'avia':
            companies = Company.objects.get(user=request.user)
            context = {
                'activities': KindOfActivity.objects.all(),
                'company': companies,
                'title': 'Главная'
            }
        else:
            companies_list = {}
            permissions = Permission.objects.filter(user=request.user)
            companies = Company.objects.all()
            for company in companies:
                has = False
                if permissions and permissions.exists():
                    for per in permissions:
                        if company == per.area.company:
                            has = True
                            break
                    if has:
                        companies_list.update({
                            company.slug: company,
                        })

            for company in companies:
                company.time_difference = company.validity - datetime.today().date()
            context = {
                'activities': KindOfActivity.objects.all(),
                'companies': companies_list,
                'title': 'Главная',
            }
    return render(request, 'products/index.html', context)


@user_passes_test(is_superuser)
def companies_list(request):
    companies = Company.objects.all()
    context = {
        'companies': companies,
        'title': 'Компании'}
    return render(request, 'users/user_list.html', context)


@user_passes_test(is_superuser)
def create_company(request):
    from products.forms import CompanyForm
    if request.method == 'POST':
        form = CompanyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('products:companies_list')  # Redirect to a success page
    else:
        form = CompanyForm()

    return render(request, 'products/register_avia.html', {'form': form, 'title': 'Регистрация'})


@user_passes_test(is_superuser)
def edit_company(request, company_slug):
    company = Company.objects.get(slug=company_slug)
    if request.method == 'POST':
        form = CompanyForm(request.POST, instance=company)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = CompanyForm(instance=company)
        form.fields.pop('password', None)  # Remove 'password' field from the form

    return render(request, 'products/register_avia.html', {'form': form, 'title': 'Регистрация'})

russian_month_names = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь']


products/templates/products/company_titles.html
{% extends 'products/base.html' %}
{% block css %}
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        h1 {
            text-align: center;
            background-color: #333;
            color: #fff;
            padding: 20px;
            margin: 0;
        }

        table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 12px 8px;
            text-align: left;
        }

        th {
            background-color: #333;
            color: #fff;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        input[type="checkbox"] {
            margin: 0;
            padding: 0;
            width: 20px;
            height: 20px;
        }

        form {
            text-align: center;
        }

        button {
            background-color: #333;
            color: #fff;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
        }

        button:hover {
            background-color: #0066cc;
        }
    </style>
{% endblock %}
{% block content %}
    <table class="my-5">
        <tr>
            <th>Заголовок</th>
            {% if request.user.is_authenticated and request.user.is_superuser %}
            <th>Доступ</th>
            {% endif %}
        </tr>
        {% if request.user.is_authenticated and request.user.is_superuser %}
        {% for title in titles %}
            <tr>

                 <td><a href="{% url 'supervision:control' company.pk %}" class="btn btn-secondary">{{ title.title }}</a></td>

                {% if request.user.is_authenticated and request.user.is_superuser %}
                <td><input type="checkbox"></td>
                {% endif %}
            </tr>
        {% endfor %}
        {% endif %}

        {% if request.user.is_authenticated and not request.user.is_superuser and user_has_access %}

                {% for title in titles %}
            <tr>

                 <td><a href="{% url 'supervision:control' company.pk %}" class="btn btn-secondary">{{ title.title }}</a></td>

                {% if request.user.is_authenticated and request.user.is_superuser %}
                <td><input type="checkbox"></td>
                {% endif %}
            </tr>
        {% endfor %}
         {% endif %}
    {% if request.user.is_superuser %}
        {% for per in perm %}
            <tr>
            <td>
                {{ per.user }}
            </td>
            </tr>
        {% endfor %}
    {% endif %}
<td>
    <a href="{% url 'supervision:control' company.pk %}" class="btn btn-secondary">{{ title.title }}</a>
    {% if request.user.is_authenticated and request.user.is_superuser %}
       <button class="grant-access-btn" data-user-id="{{ user_id }}" data-url="{% url 'products:grant_access' %}">Предоставить доступ</button>

    {% endif %}
</td>


    </table>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>

fetch("{% url 'products:grant_access' %}")

</script>


{% endblock %}


products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}
{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/products.css' %}" rel="stylesheet"/>
    <style>
        .col {
            display: grid;
            grid-template-columns: 1fr 1fr 1fr;
            justify-content: space-evenly;
            column-gap: 10px;
            row-gap: 20px;
        }

        @media screen and (max-width: 768px) {
            .col {
                grid-template-columns: 1fr 1fr;
            }
        }

        @media screen and (max-width: 480px) {
            .col {
                grid-template-columns: 1fr;
            }
            .unauth{
                font-size:large;
            }
        }

        .card {
            --main-focus: #2B4156;
            --font-color: #323232;
            --font-color-sub: #666;
            --bg-color: #0261A9;
            --main-color: #323232;
            font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            width: 250px;
            height: 100%;
            margin: 0 auto;
            background: transparent;
            border: 2px solid var(--main-color);
            box-shadow: 4px 4px var(--main-color);
            border-radius: 5px;
            padding: 10px;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

        .card-content-wrapper {
            transform: translateY(10px);
            display: flex;
            flex-direction: column;
            gap: 5px;
            transition: all 0.7s;
        }

        .card-title {
            letter-spacing: 3px;
            font-size: 17px;
            font-weight: 700;
            color: var(--font-color);
        }

        .card-price {
            letter-spacing: 2px;
            font-size: 20px;
            line-height: 15px;
            margin-bottom: 5px;
            color: var(--font-color);
            font-weight: 700;
        }

        .card-price span {
            font-size: 15px;
            color: var(--font-color-sub);
            font-weight: 500;
        }


        .card-benefits {
            font-size: 15px;
            padding-left: 20px;
            color: var(--font-color);
        }

        .card-btn {
            cursor: pointer;
            width: auto;
            padding: 5px 15px;
            background: var(--main-focus);
            border: none;
            border-radius: 10px;
            margin: 0 auto;
            color: white;
            font-weight: 500;
            font-size: 12px;
            letter-spacing: 0.7px;
            transition: all 0.7s;
        }

        .card > .card-btn {
            opacity: 1;
        }

        .card-btn:hover {
            color: white;
            background-color: var(--bg-color);
            font-weight: 700;
            letter-spacing: 1px;
        }

        .card:hover > .card-content-wrapper {
            transform: translateY(5px);
        }
        .card-footer{
            padding-bottom: 0;
            display: flex;
            flex-direction: column;
            border: none !important;
            color: #0f0f0f;
            background-color: transparent !important;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container-sm mt-5">
        <img src="/media/img/plane_0.png" class="img-fluid mx-auto d-block" alt="...">
        <div class="overlay"></div>
    </div>
    {% if request.user.is_authenticated %}
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <br>
                    <h1 class="text-center">Авиакомпании <br> Кыргызской Республики</h1>
                    <br>
                </div>
            </div>

            {% if request.user.groups.all.first.name == 'avia' %}
                <div class="card">
                    <div class="card-content-wrapper">
                        <div class="card-title"> {{ forloop.counter }}. {{ company.name }}</div>
                        <div class="card-price">
                            <span>{{ company.kind_of_activity }}</span>
                        </div>
                        <ul class="card-benefits">
                            <li>{{ company.time_difference.days }} дня до окончания сертификата эксплуатанта</li>
                            <li>Статус СЕ:
                                {% if company.status %}
                                    Действующий
                                {% else %}
                                    Приостановлен
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'products:edit_company' company.slug %}" class="card-btn mb-1">Подробнее</a>
                        <a href="{% url 'supervision:control' company.slug %}" class="card-btn">Надзор</a></div>
                </div>
            {% elif request.user.is_superuser %}
                <div class="col">
                    {% for company in companies %}
                        <div class="card">
                            <div class="card-content-wrapper">
                                <div class="card-title"> {{ forloop.counter }}. {{ company.name }}</div>
                                <div class="card-price">
                                    <span>{{ company.kind_of_activity }}</span>
                                </div>
                                <ul class="card-benefits">
                                    <li>{{ company.time_difference.days }} дня до окончания сертификата эксплуатанта
                                    </li>
                                    <li>Статус СЕ:
                                        {% if company.status %}
                                            Действующий
                                        {% else %}
                                            Приостановлен
                                        {% endif %}
                                    </li>
                                </ul>
                            </div>
                            <div class="card-footer">
                                <a href="{% url 'products:edit_company' company.slug %}" class="card-btn mb-1">Подробнее</a>
                                <a href="{% url 'supervision:control' company.slug %}" class="card-btn">Надзор</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="col">
                    {% for key, company in companies.items %}
                        <div class="card">
                            <div class="card-content-wrapper">
                                <div class="card-title"> {{ forloop.counter }}. {{ company.name }}</div>
                                <div class="card-price">
                                    <span>{{ company.kind_of_activity }}</span>
                                </div>
                                <ul class="card-benefits">
                                    <li>{{ company.time_difference.days }} дня до окончания сертификата эксплуатанта
                                    </li>
                                    <li>Статус СЕ:
                                        {% if company.status %}
                                            Действующий
                                        {% else %}
                                            Приостановлен
                                        {% endif %}
                                    </li>
                                </ul>
                            </div>

                            <div class="card-footer">
                                <a href="{% url 'products:edit_company' company.slug %}" class="card-btn mb-1">Подробнее</a>
                                <a href="{% url 'supervision:control' company.slug %}" class="card-btn">Надзор</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    {% else %}
        <div class="container mt-5">
        <div class="m-auto d-flex text-center">
            <h2 class="m-auto unauth">
                Добро пожаловать в сайт Отдел летной эксплуатации (OPS)!
            </h2>
        </div>
        <div class="m-auto d-flex py-5">
            <p class="m-auto text-primary text-center">
                Чтобы продолжить <a class="alert-link" href="{% url 'users:login' %}">войдите</a>
            </p>

        </div>
    {% endif %}
{% endblock %}

products/templates/products/register_avia.html
{% extends 'products/base.html' %}
{% load static %}

{% block content  %}
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container mt-5">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors}}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endif %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-5">Форма компании</h3>
                            </div>
                            <div class="card-body">
                                <form method="post" onsubmit="register.disabled = true; return true;">
                                    {% csrf_token %}
                                    <div class="input-group">
                                    {% for field in form %}
                                        {% if field.name != 'status' and field.name != 'code' and field.name != 'validity' %}
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                                    {{ field }}
                                                </div>
                                            </div>
                                        {% else %}
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label class="small mb-1" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                                    {{ field }}
                                                </div>
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                    </div>

                                    <div class="form-group d-flex col-12">
                                        <input class="btn btn-primary btn-block m-auto" type="submit" value="Сохранить компанию" id="register">
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
{% endblock %}